[toolchain]
package_manager = "pnpm"
anchor_version = "0.31.1"

[features]
resolution = true
skip-lint = false

[workspace]
members = ["programs/*"]

[programs.localnet]
counter = "EWgXrGEdzQMqbSqSk8mEwQvKxBNFrpo8X7PDHiXrrvge"

[programs.devnet]
counter = "EWgXrGEdzQMqbSqSk8mEwQvKxBNFrpo8X7PDHiXrrvge"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
